In [3]:
pip install scikit-learn 

Note: you may need to restart the kernel to use updated packages.


In [10]:
pip show scikit-learn

Name: scikit-learnNote: you may need to restart the kernel to use updated packages.

Version: 1.5.1
Summary: A set of python modules for machine learning and data mining
Home-page: https://scikit-learn.org
Author: 
Author-email: 
License: new BSD
Location: C:\Users\GTEX\anaconda3\Lib\site-packages
Requires: joblib, numpy, scipy, threadpoolctl
Required-by: imbalanced-learn


In [11]:
# 학습할 데이터를 입력 후 모델 생성하기
from sklearn import tree

# 학습 데이터
# 귀모양, 수염길이, 입이 나옴, 호피무늬, 꼬리 길이
x = [ [0,1,0,1,1], [0,1,0,0,0],[1,0,1,0,0]]
# 정답 데이터
y = [2,2,1]

# 결정 트리에 의해 학습
c = tree.DecisionTreeClassifier()
c=c.fit(x,y)

# 새로운 데이터를 생성한 학습 모델에 넣어 결과 예측하기
c.predict([[1,1,0,0,1]])

array([2])

In [12]:
# 귀모양 원형, 수염길이 짧고, 입이 나오지 않았고, 호피무늬가 아니고, 꼬리가 짧은 동물
c.predict([[1,0,0,0,0]])

array([1])

In [13]:
# 귀모양 원형, 수염길이 짧고, 입이 나오고, 호피무늬고, 꼬리가 짧은 동물
c.predict([[1,0,1,1,0]])

array([1])

In [14]:
# 귀모양 원형, 수염길이 길고, 입이 나오고, 호피무늬가 아니고, 꼬리가 짧은 동물
c.predict([[1,1,1,0,0]])

array([2])

In [24]:
# page.250 mission
from sklearn import tree


# 1. 자녀의 키가 속하는 그룹을 예측하는 코드 작성하기
# 3 : 키가 큰 키, 2 : 중간 키, 1 : 작은 키
x = [ [180, 165], [175, 160], [180, 172], [165, 160], [171, 152] ]
y = [ 3, 2, 2, 1, 1]

z = tree.DecisionTreeClassifier()
z = z.fit(x,y)
z.predict([[175,153]])

array([2])

In [21]:
# 2. 자동차와 컵을 구분하는 코드 작성하기
# 1 : 컵, 2 : 자동차
a = [ [0,1,1,1,1], [1,1,1,1,0], [0,1,1,0,0] ]
b = [1,2,2]

c = tree.DecisionTreeClassifier()
c = c.fit(a,b)
c.predict([[0,1,1,1,0]])

array([2])

In [22]:
# 3. 다이어트 방법이 건강한지 여부를 판단하는 코드 작성하기
# 1: 건강, 0: 미흡
h = [ [0, 0, 1, 1, 1, 1], [0, 0, 1, 0, 0, 1], [1, 1, 1, 1, 0, 0], [1, 1, 0, 1, 0, 0], [0, 0, 0, 0, 0, 1] ]
j = [ 1, 1, 0, 0, 1]

k = tree.DecisionTreeClassifier()
k = k.fit(h,j)
k.predict([[0,0,1,0,1,0]])

array([0])

In [23]:
k.predict([[1,0,1,0,0,0]])

array([0])