In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [22]:
import numpy as np

# 0~10까지 2씩 증가한 결과를 arr변수에 저장
arr = np.arange(0,11,2)

print(np.sum(arr)) # 0, 2, 4, 6, 8, 10 값 합계
print(np.mean(arr)) # 0, 2, 4, 6, 8, 10 값 평균
print(np.max(arr)) # 0, 2, 4, 6, 8, 10 값 중 가장 큰 값
print(np.min(arr)) # 0, 2, 4, 6, 8, 10 값 중 가장 작은 값
print(np.var(arr)) # 0, 2, 4, 6, 8, 10 분산
print(np.std(arr)) # 0, 2, 4, 6, 8, 10 값 표준편차
# 리스트 자료형에 저장되어 있는 값을 합계와 평균을 계산하기 위해서는 numpy자료형으로 저장 
arr1 = np.array([1,2,3])
arr2 = np.array([1.2,2.3,3.5])
arr3 = np.array([[1,2,3],[4,5,6]])

print(arr1)
print(arr2)
print(arr3)

30
5.0
10
0
11.666666666666666
3.415650255319866
[1 2 3]
[1.2 2.3 3.5]
[[1 2 3]
 [4 5 6]]


In [30]:
# 리스트 0~10까지 2만큼 증가하는 항목을 갖는 리스트
n = list(range(0,11,2))
n

[0, 2, 4, 6, 8, 10]

In [24]:
# 타입을 출력
lst = [1,2,3]
arr = np.array(lst)
print(type(lst))
print(type(arr))

arr4 = np.arange(1,10)
arr5 = np.linspace(0,0.9,4)   # 0~0.9를 4등분

print(arr4)
print(arr5)

# 0~10까지 2씩 증가하는 리스트 n
n = list(range(0,11,2))

# n의 각 항목을 2만큼 증가
for i in range(len(n)):
    n[i] = n[i] + 2
n


<class 'list'>
<class 'numpy.ndarray'>
[1 2 3 4 5 6 7 8 9]
[0.  0.3 0.6 0.9]


[2, 4, 6, 8, 10, 12]

In [29]:
# 0부터 1까지 0.2씩 증가하는 항목
arr1 = np.arange(0,1.1,0.2)
# 6개의 1을 갖는 배열
arr2 = np.ones(6)

print(arr + 0.1)
print(arr1 + arr2)


[1.1 2.1 3.1]
[1.  1.2 1.4 1.6 1.8 2. ]


In [21]:
# zeros : 3만큼  0으로 초기화된 배열 생성
arr6 = np.zeros(3)
print(arr6)
arr7 = np.zeros(3, dtype = "int")
print(arr7)

# 2만큼 1로 초기화된 배열 생성
arr8 = np.ones([2,2])
print(arr8)

# 2 형태로 초기화하지 않은 배열 생성
arr9 = np.empty(2)
print(arr9)

[0. 0. 0.]
[0 0 0]
[[1. 1.]
 [1. 1.]]
[1.40845691 1.42963398]


In [48]:
# 넘파이의 array()를 사용하여 넘파이 배열 생성하기
arr1 = np.array([1,2,3])
arr2 = np.array([1.2,2.3,3.5])
arr3 = np.array([[1,2,3],[4,5,6]])

print(arr1)
print(arr2)
print(arr3)

[1 2 3]
[1.2 2.3 3.5]
[[1 2 3]
 [4 5 6]]


In [53]:
# arange()/linspace()를 사용하여 배열 생성하기
arr1 = np.arange(1,10)
arr2 = np.arange(1,10,2)
arr3 = np.linspace(0,0.9,4)

print(arr1)
print(arr2)
print(arr3)

[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
[0.  0.3 0.6 0.9]


In [56]:
# zeros()/ ones()/ empty()를 사용하여 배열 생성

arr1 = np.zeros(3)
arr2 = np.zeros([2,3], dtype=int)
arr3 = np.ones([2,2])
arr4 = np.empty(2)

print(arr1)
print(arr2)
print(arr3)
# 메모리에 있는 임의의 값이 출력되기 때문에 결과가 다 다름
print(arr4)


[0. 0. 0.]
[[0 0 0]
 [0 0 0]]
[[1. 1.]
 [1. 1.]]
[0.3 0.6]


In [20]:
# rand() / randn() / randint()를 사용하여 배열 생성

# 0~1 사이의 랜덤값
arr10 = np.random.rand(2)

# 분산 결과의 값을 랜덤값
arr11 = np.random.randn(2)

# 1~10 사의의 랜덤값, 그 결과는 3가지
arr12 = np.random.randint(1,10,size=3)
# 0~10 사의의 랜덤값, 2행 2열의 2차원으로 결과
arr13 = np.random.randint(10,size=(2,2))

print(arr10)
print(arr11)
print(arr12)
print(arr13)

[0.20870645 0.72011226]
[-1.40845691 -1.42963398]
[6 2 4]
[[8 3]
 [9 0]]


In [57]:
# 항목값이 모두 1인 2차원 배열을 생성하고 그 배열의 속성값 출력하기

arr1 = np.ones([3,4])

print(arr1)
print(arr1.size)
print(arr1.dtype)
print(arr1.shape)
print(arr1.ndim)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
12
float64
(3, 4)
2


In [59]:
# 2차원 배열을 생성하고 인덱싱과 슬라이싱을 사용하여 배열의 일부분만 출력

arr1 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print(arr1[0])
print(arr1[0,2])
print(arr1[1:])
print(arr1[arr1>5])


[1 2 3]
3
[[4 5 6]
 [7 8 9]]
[6 7 8 9]


In [66]:
# 배열 항목의 행/열을 서로 교환한 배열, 
# 3행 2열 형태로 재구성한 배열, 
# 1차원 배열로 재구성한 배열을 생성하여 출력하기

arr = np.array([[1,2,3], [4,5,6]])

arr_T = arr.transpose()
arr_R = arr.reshape(3,2)
arr_F = arr.flatten()

print(arr,"\n")
print(arr_T,"\n")
print(arr_R,"\n")
print(arr_F,"\n")


[[1 2 3]
 [4 5 6]] 

[[1 4]
 [2 5]
 [3 6]] 

[[1 2]
 [3 4]
 [5 6]] 

[1 2 3 4 5 6] 



In [68]:
# 두 배열에 대한 덧셈,뺄셈,크기 비교 연사나 결과를 출력
arr1 = np.arange(1,5)
arr2 = np.ones(4)

print(arr1, arr2)
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 > arr2)

[1 2 3 4] [1. 1. 1. 1.]
[2. 3. 4. 5.]
[0. 1. 2. 3.]
[False  True  True  True]


In [69]:
# 배열에 2를 더하고 2를 곱한 결과 출력

arr1 = np.random.randint(11, size=4)

print(arr1)
print(arr1 + 2)
print(arr1 * 2)

[6 0 6 2]
[8 2 8 4]
[12  0 12  4]


In [70]:
# 배열의 항목들 중에서 최솟값과 최댓값을 출력하고, 
# 항목들의 합계와 산술평균, 분산,표준편차를 계산한 결과 출력

arr1= np.random.randint(-10, 11, size=5)

print(arr1)
print(np.min(arr1))
print(np.max(arr1))
print(np.sum(arr1))
print(np.mean(arr1))
print(np.var(arr1))
print(np.std(arr1))

[-5  2  2 -4 -6]
-6
2
-11
-2.2
12.16
3.4871191548325386


In [77]:
# 넘파이 배열의 연산 연습

국어 = np.array([20,30,60])
영어 = np.array([60,40,90])

print(국어)
print(영어)

총점 = 국어 + 영어
평균 = 총점 / 2

print(총점)
print(평균)

print(np.mean(국어))

[20 30 60]
[60 40 90]
[ 80  70 150]
[40. 35. 75.]
36.666666666666664


In [46]:
# page102 연습문제
# 1.
arr2 = np.array([[1,2,3],[4,5,6]])
arr2 = arr2.flatten()*2
print("1번", arr2)

#3.
arr = np.arange(5,30,5)
print("3번", arr)

#5.
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("5번",arr1)

print("5-1번",arr1[1])
print("5-2번",arr1[2,2])
print("5-3번",arr1[1:3])
print("5-4번",arr1[arr1 <= 5])

1번 [ 2  4  6  8 10 12]
3번 [ 5 10 15 20 25]
5번 [[1 2 3]
 [4 5 6]
 [7 8 9]]
5-1번 [4 5 6]
5-2번 9
5-3번 [[4 5 6]
 [7 8 9]]
5-4번 [1 2 3 4 5]


In [47]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.
